using System.ComponentModel.DataAnnotations.Schema;

namespace EShop.Models
{
    public abstract class BaseEntity : IBaseEntity
    {
        /*The Identity option specifies that the value will only be generated by the database when 
           a value is first added to the database. Thereafter, the property will not be included in 
           UPDATE statements by Entity Framework.*/
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string? Id { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}
